MAKE NUMBER input 2;
MAKE NUMBER factor 32;
MAKE NUMBER intMax 0;
DO "pow" :input,factor: TO intMax;
DO SET intMax :intMax/2:;
DO SAY "The\sinterger\slimit\sis:\s";
DO SAY intMax;
>> DO "hello" ::;
>> MAKE DOUBLE response 0;
>> DO "whatIsOnePlusOne" :: TO response;
>> DO SAY response;
END 0;
DEFINE FUNC DOUBLE pow :in,fac:;
    MAKE NUMBER one 1;
    SKIP LOCATION returnLoop;
        DO SET in :in*in:;
        DO SET fac :fac-1:;
    SKIP TO "returnLoop" WHEN @fac>one@;
    DO RETURN in;
ENDFUNC;
DEFINE FUNC VOID hello ::;
    DO SAY "Hello\sfrom\sfunction!\n";
    DO RETURN;
ENDFUNC;
DEFINE FUNC DOUBLE whatIsOnePlusOne ::;
    MAKE DOUBLE res 2;
    DO RETURN res;
ENDFUNC;